[package]
name = "kalk"
version = "0.1.0"
edition = "2024"
authors = ["yfloress"]
description = "Manage courses, track grades, and automatically calculate the exact threshold needed to pass, all without touching the mouse."
license = "AGPL-3.0-or-later"
repository = "https://github.com/yfloress/Kalk"
readme = "README.md"
keywords = ["tui", "academic", "productivity", "grades", "ratatui"]
categories = ["command-line-utilities", "visualization"]

exclude = [
    ".img/*",
    ".envrc"
]

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "6.0"
uuid = { version = "1.23", features = ["v4", "serde"] }
color-eyre = "0.6.5"
